### ISSUE TITLE
Provide more context to this repo

### ISSUE THREAD

**Issue by sidkshatriya** [emillon/js-monorepo#15]
I chanced upon this repository because it was linked from https://github.com/ocaml/ocaml/pull/10718#issue-1031394635

This repository could be useful for the wider OCaml community. If it is possible, may I request that a bit more context is provided in a README?

In particular 
- How is this different from https://github.com/janestreet/universe ?
- How does it track Janestreet packages? 
- What scenarios might we want to use this monorepo?
- Any additional information you feel necessary

Thanks!

**Comment by emillon** [comment]
Hi,
This is a way to build lots of ocaml code in a single dune workspace. It is not looking for more users at this stage. Thanks for your interest!
